/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


// Generated by generate_test_data.py using TFL version 2.3.0 as reference.
#pragma once
#define CONV_1616_3232_OUT_CH 32
#define CONV_1616_3232_IN_CH 32
#define CONV_1616_3232_INPUT_W 16
#define CONV_1616_3232_INPUT_H 16
#define CONV_1616_3232_DST_SIZE 6272
#define CONV_1616_3232_INPUT_SIZE 8192
#define CONV_1616_3232_OUT_ACTIVATION_MIN -128
#define CONV_1616_3232_OUT_ACTIVATION_MAX 127
#define CONV_1616_3232_INPUT_BATCHES 1
#define CONV_1616_3232_INPUT_OFFSET 0
#define CONV_1616_3232_OUTPUT_OFFSET 0
#define CONV_1616_3232_FILTER_X 3
#define CONV_1616_3232_FILTER_Y 3
#define CONV_1616_3232_STRIDE_X 1
#define CONV_1616_3232_STRIDE_Y 1
#define CONV_1616_3232_PAD_X 0
#define CONV_1616_3232_PAD_Y 0
#define CONV_1616_3232_OUTPUT_W 14
#define CONV_1616_3232_OUTPUT_H 14
