/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


// Generated by resnet_data_gen.py using TFL version 2.3.0 as reference.
#pragma once
#include <stdint.h>

const int32_t convlayer1_biases[32] =
{
  2699,
  -5398,
  2699,
  -2699,
  -2699,
  2699,
  -5398,
  0,
  0,
  0,
  0,
  -2699,
  2699,
  -5398,
  -2699,
  -2699,
  0,
  0,
  -5398,
  -2699,
  2699,
  -5398,
  -2699,
  -2699,
  2699,
  0,
  -5398,
  2699,
  2699,
  -2699,
  -2699,
  2699
};
const int32_t convlayer2_biases[32] =
{
  0,
  -5398,
  -5398,
  0,
  -5398,
  -5398,
  0,
  2699,
  0,
  -2699,
  -2699,
  -2699,
  -5398,
  0,
  2699,
  2699,
  -5398,
  2699,
  -5398,
  2699,
  2699,
  -2699,
  -5398,
  -2699,
  0,
  -5398,
  2699,
  -2699,
  -5398,
  -2699,
  -2699,
  2699
};
const int32_t convlayer3_biases[64] =
{
  0,
  -5398,
  2699,
  0,
  -2699,
  2699,
  2699,
  -5398,
  -5398,
  2699,
  -5398,
  0,
  -5398,
  0,
  -2699,
  2699,
  -5398,
  0,
  -5398,
  -2699,
  2699,
  -2699,
  -2699,
  -5398,
  2699,
  2699,
  2699,
  -5398,
  0,
  -5398,
  2699,
  -2699,
  2699,
  0,
  -2699,
  -2699,
  0,
  -5398,
  -5398,
  -5398,
  -2699,
  2699,
  -2699,
  -5398,
  -2699,
  -2699,
  -5398,
  -2699,
  2699,
  -5398,
  0,
  -2699,
  2699,
  -2699,
  0,
  0,
  0,
  2699,
  0,
  -5398,
  -5398,
  -2699,
  0,
  -2699
};
