/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


// Generated by resnet_data_gen.py using TFL version 2.3.0 as reference.
#pragma once
#define CONVLAYER1_OUT_CH 32
#define CONVLAYER1_IN_CH 3
#define CONVLAYER1_INPUT_W 32
#define CONVLAYER1_INPUT_H 32
#define CONVLAYER1_DST_SIZE 32768
#define CONVLAYER1_INPUT_SIZE 3072
#define CONVLAYER1_OUT_ACTIVATION_MIN -128
#define CONVLAYER1_OUT_ACTIVATION_MAX 127
#define CONVLAYER1_INPUT_BATCHES 1
#define CONVLAYER1_INPUT_OFFSET 0
#define CONVLAYER1_OUTPUT_OFFSET 0
#define CONVLAYER1_FILTER_X 5
#define CONVLAYER1_FILTER_Y 5
#define CONVLAYER1_STRIDE_X 1
#define CONVLAYER1_STRIDE_Y 1
#define CONVLAYER1_PAD_X 2
#define CONVLAYER1_PAD_Y 2
#define CONVLAYER1_OUTPUT_W 32
#define CONVLAYER1_OUTPUT_H 32
#define CONVLAYER2_OUT_CH 32
#define CONVLAYER2_IN_CH 32
#define CONVLAYER2_INPUT_W 16
#define CONVLAYER2_INPUT_H 16
#define CONVLAYER2_DST_SIZE 8192
#define CONVLAYER2_INPUT_SIZE 8192
#define CONVLAYER2_OUT_ACTIVATION_MIN -128
#define CONVLAYER2_OUT_ACTIVATION_MAX 127
#define CONVLAYER2_INPUT_BATCHES 1
#define CONVLAYER2_INPUT_OFFSET 0
#define CONVLAYER2_OUTPUT_OFFSET 0
#define CONVLAYER2_FILTER_X 5
#define CONVLAYER2_FILTER_Y 5
#define CONVLAYER2_STRIDE_X 1
#define CONVLAYER2_STRIDE_Y 1
#define CONVLAYER2_PAD_X 2
#define CONVLAYER2_PAD_Y 2
#define CONVLAYER2_OUTPUT_W 16
#define CONVLAYER2_OUTPUT_H 16
#define CONVLAYER3_OUT_CH 64
#define CONVLAYER3_IN_CH 32
#define CONVLAYER3_INPUT_W 8
#define CONVLAYER3_INPUT_H 8
#define CONVLAYER3_DST_SIZE 4096
#define CONVLAYER3_INPUT_SIZE 2048
#define CONVLAYER3_OUT_ACTIVATION_MIN -128
#define CONVLAYER3_OUT_ACTIVATION_MAX 127
#define CONVLAYER3_INPUT_BATCHES 1
#define CONVLAYER3_INPUT_OFFSET 0
#define CONVLAYER3_OUTPUT_OFFSET 0
#define CONVLAYER3_FILTER_X 5
#define CONVLAYER3_FILTER_Y 5
#define CONVLAYER3_STRIDE_X 1
#define CONVLAYER3_STRIDE_Y 1
#define CONVLAYER3_PAD_X 2
#define CONVLAYER3_PAD_Y 2
#define CONVLAYER3_OUTPUT_W 8
#define CONVLAYER3_OUTPUT_H 8
